/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package studentmanager.EntryForm;

import studentmanager.JavaClasses.Department;
import studentmanager.JavaClasses.Course;
import java.awt.Dimension;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import studentmanager.Repository.Repository;

/**
 *
 * @author fes77
 */
public class DepartmentEntry extends javax.swing.JPanel {

    /**
     * Creates new form DepartmentEntry
     */
    private JFrame frame;

    public DepartmentEntry() {
        frame = new JFrame("Department Entry Form");

        initComponents();
    }

    public void exec() {
        frame.setSize(new Dimension(500, 300));
        frame.setContentPane(this);
        frame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        frame.pack();
        frame.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        departmentIDLabel = new javax.swing.JLabel();
        departmentIDEntry = new javax.swing.JTextField();
        departmentNameLabel = new javax.swing.JLabel();
        departmentNameEntry = new javax.swing.JTextField();
        okButton = new javax.swing.JButton();

        departmentIDLabel.setFont(new java.awt.Font("MS UI Gothic", 0, 14)); // NOI18N
        departmentIDLabel.setText("Department ID");

        departmentIDEntry.setFont(new java.awt.Font("MS UI Gothic", 0, 14)); // NOI18N

        departmentNameLabel.setFont(new java.awt.Font("MS UI Gothic", 0, 14)); // NOI18N
        departmentNameLabel.setText("Department Name");

        departmentNameEntry.setFont(new java.awt.Font("MS UI Gothic", 0, 14)); // NOI18N

        okButton.setText("OK");
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(departmentIDLabel)
                            .addComponent(departmentNameLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(departmentNameEntry, javax.swing.GroupLayout.DEFAULT_SIZE, 266, Short.MAX_VALUE)
                            .addComponent(departmentIDEntry)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(okButton)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(departmentIDLabel)
                    .addComponent(departmentIDEntry, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(departmentNameLabel)
                    .addComponent(departmentNameEntry, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(okButton)
                .addGap(21, 21, 21))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        // TODO add your handling code here:
        System.out.println(departmentIDEntry.getText());
        if (departmentIDEntry.getText().equals("") || departmentNameEntry.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Empty input");
            return;
        }

        // Check for duplicate entry
        try {
            String id = departmentIDEntry.getText();
            for (Department dept : Repository.findAllDepartments()) {
                if(dept.getDepartmentID().equals(id))
                {
                    JOptionPane.showMessageDialog(null, "Duplication Entry :" + dept.toString());
                    return;
                }
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Connection Error");
        }

        frame.dispose();
        System.out.println("Ended");
        java.util.List<Course> courseList = new ArrayList<>();
        Department department = new Department(departmentIDEntry.getText(), departmentNameEntry.getText());
        System.out.println(department);
    }//GEN-LAST:event_okButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField departmentIDEntry;
    private javax.swing.JLabel departmentIDLabel;
    private javax.swing.JTextField departmentNameEntry;
    private javax.swing.JLabel departmentNameLabel;
    private javax.swing.JButton okButton;
    // End of variables declaration//GEN-END:variables
}
