/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package studentmanager;

import java.awt.*;
import java.time.DayOfWeek;
import java.time.LocalTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.Arrays;
import javax.swing.*;

/**
 *
 * @author fes77
 */
public class CourseEntry extends javax.swing.JPanel {

    /**
     * Creates new form CourseEntry
     */
    DefaultComboBoxModel<Professor> professorModel;
    DefaultComboBoxModel<Department> departmentModel;
    DefaultComboBoxModel<Semester> semesterModel;
    boolean active;
    
    public CourseEntry() {
        active = true;
        
        departmentModel = new DefaultComboBoxModel<>();
        for(Department d :TestRepository.getDepartments())
        {
            departmentModel.addElement(d);
        }
        
        professorModel = new DefaultComboBoxModel<>();
        for(Professor f : TestRepository.getProfessors())
        {
            professorModel.addElement(f);
        }
        
        semesterModel = new DefaultComboBoxModel<>();
        for(Semester s : TestRepository.getSemesters())
        {
            semesterModel.addElement(s);
        }
        
        initComponents();
    }

    public JPanel getMainPanel() {
        return mainPanel;
    }

    public boolean isActive() {
        return active;
    }

    public void setActive(boolean active) {
        this.active = active;
    }
    
    public Course exec()
    {
        JFrame frame = new JFrame("Course Entry");
        frame.setSize(new Dimension(500, 300));
        frame.setContentPane(this.getMainPanel());
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.pack();
        frame.setVisible(true);
        while(true)
        {

            try {
             Thread.sleep(10);
            } catch (InterruptedException e) {
            }
            if(!isActive())
            {
                if(courseNumEntry.getText().isEmpty())
                {
                    JOptionPane.showMessageDialog(null, "Empty Course Number is not allowed");
                    setActive(true);
                }
                else{
                    break;
                }
                
            }
        }
        frame.dispose();
        java.util.List<DayOfWeek> days = new ArrayList<>();
        
        if(sunRadio.isSelected())
            days.add(DayOfWeek.SUNDAY);
        if(monRadio.isSelected())
            days.add(DayOfWeek.MONDAY);
        if(tueRadio.isSelected())
            days.add(DayOfWeek.TUESDAY);
        if(wedRadio.isSelected())
            days.add(DayOfWeek.WEDNESDAY);
        if(thuRadio.isSelected())
            days.add(DayOfWeek.THURSDAY);
        if(friRadio.isSelected())
            days.add(DayOfWeek.FRIDAY);
        if(satRadio.isSelected())
            days.add(DayOfWeek.SATURDAY);
        
        
        return new Course((Department)departmentCmbbox.getSelectedItem(), 
            new Integer(courseNumEntry.getValue().toString()), 
            titleEntry.getText(),
            professorCmbbox.getItemAt(professorCmbbox.getSelectedIndex()),
            semesterCmbbox.getItemAt(semesterCmbbox.getSelectedIndex()),
            new Schedule(days, (String)timeStartHourCmb.getSelectedItem(), 
                    (String)timeStartMinuteCmb.getSelectedItem(), 
                    (String)timeStartAMPM.getSelectedItem(),  
                    (String)timeEndHourCmb.getSelectedItem(),
                    (String)timeEndMinuteCmb.getSelectedItem(),
                    (String)timeEndAMPM.getSelectedItem()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jOptionPane1 = new javax.swing.JOptionPane();
        mainPanel = new javax.swing.JPanel();
        departmentLabel = new javax.swing.JLabel();
        courseNumLabel = new javax.swing.JLabel();
        departmentCmbbox = new javax.swing.JComboBox<>();
        titleLabel = new javax.swing.JLabel();
        titleEntry = new javax.swing.JTextField();
        daysLabel = new javax.swing.JLabel();
        timeLabel = new javax.swing.JLabel();
        semesterLabel = new javax.swing.JLabel();
        semesterCmbbox = new javax.swing.JComboBox<>();
        semesterAddButton = new javax.swing.JButton();
        professorLabel = new javax.swing.JLabel();
        professorCmbbox = new javax.swing.JComboBox<>();
        professorAddButton = new javax.swing.JButton();
        departmentAddButton = new javax.swing.JButton();
        submitButton = new javax.swing.JButton();
        daysRadioPanel = new javax.swing.JPanel();
        sunRadio = new javax.swing.JRadioButton();
        monRadio = new javax.swing.JRadioButton();
        tueRadio = new javax.swing.JRadioButton();
        wedRadio = new javax.swing.JRadioButton();
        satRadio = new javax.swing.JRadioButton();
        friRadio = new javax.swing.JRadioButton();
        thuRadio = new javax.swing.JRadioButton();
        timePanel = new javax.swing.JPanel();
        timeStartAMPM = new javax.swing.JComboBox<>();
        timeEndAMPM = new javax.swing.JComboBox<>();
        timeStartLabel = new javax.swing.JLabel();
        timeEndHourCmb = new javax.swing.JComboBox<>();
        timeEndLabel = new javax.swing.JLabel();
        timeEndMinuteCmb = new javax.swing.JComboBox<>();
        timeStartHourCmb = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        timeStartMinuteCmb = new javax.swing.JComboBox<>();
        courseNumEntry = new javax.swing.JFormattedTextField();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        departmentLabel.setFont(new java.awt.Font("MS UI Gothic", 0, 14)); // NOI18N
        departmentLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        departmentLabel.setText("Department");
        departmentLabel.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        courseNumLabel.setFont(new java.awt.Font("MS UI Gothic", 0, 14)); // NOI18N
        courseNumLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        courseNumLabel.setText("Course Number");
        courseNumLabel.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        departmentCmbbox.setFont(new java.awt.Font("MS UI Gothic", 0, 14)); // NOI18N
        departmentCmbbox.setModel(departmentModel);
        departmentCmbbox.setSelectedItem(departmentModel);

        titleLabel.setFont(new java.awt.Font("MS UI Gothic", 0, 14)); // NOI18N
        titleLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        titleLabel.setText("Title");
        titleLabel.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        titleEntry.setFont(new java.awt.Font("MS UI Gothic", 0, 14)); // NOI18N
        titleEntry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                titleEntryActionPerformed(evt);
            }
        });

        daysLabel.setFont(new java.awt.Font("MS UI Gothic", 0, 14)); // NOI18N
        daysLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        daysLabel.setText("Days");
        daysLabel.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        timeLabel.setFont(new java.awt.Font("MS UI Gothic", 0, 14)); // NOI18N
        timeLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        timeLabel.setText("Time");
        timeLabel.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        semesterLabel.setFont(new java.awt.Font("MS UI Gothic", 0, 14)); // NOI18N
        semesterLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        semesterLabel.setText("Semester");
        semesterLabel.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        semesterCmbbox.setFont(new java.awt.Font("MS UI Gothic", 0, 14)); // NOI18N
        semesterCmbbox.setModel(semesterModel);

        semesterAddButton.setText("+");
        semesterAddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                semesterAddButtonActionPerformed(evt);
            }
        });

        professorLabel.setFont(new java.awt.Font("MS UI Gothic", 0, 14)); // NOI18N
        professorLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        professorLabel.setText("Professor");
        professorLabel.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        professorCmbbox.setFont(new java.awt.Font("MS UI Gothic", 0, 14)); // NOI18N
        professorCmbbox.setModel(professorModel);

        professorAddButton.setText("+");
        professorAddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                professorAddButtonActionPerformed(evt);
            }
        });

        departmentAddButton.setText("+");
        departmentAddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                departmentAddButtonActionPerformed(evt);
            }
        });

        submitButton.setText("Submit");
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });

        sunRadio.setText("Sun");
        sunRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sunRadioActionPerformed(evt);
            }
        });

        monRadio.setText("Mon");
        monRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                monRadioActionPerformed(evt);
            }
        });

        tueRadio.setText("Tue");
        tueRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tueRadioActionPerformed(evt);
            }
        });

        wedRadio.setText("Wed");
        wedRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wedRadioActionPerformed(evt);
            }
        });

        satRadio.setText("Sat");
        satRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                satRadioActionPerformed(evt);
            }
        });

        friRadio.setText("Fri");
        friRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                friRadioActionPerformed(evt);
            }
        });

        thuRadio.setText("Thu");
        thuRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                thuRadioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout daysRadioPanelLayout = new javax.swing.GroupLayout(daysRadioPanel);
        daysRadioPanel.setLayout(daysRadioPanelLayout);
        daysRadioPanelLayout.setHorizontalGroup(
            daysRadioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, daysRadioPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(sunRadio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(monRadio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tueRadio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(wedRadio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(thuRadio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(friRadio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(satRadio))
        );
        daysRadioPanelLayout.setVerticalGroup(
            daysRadioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(daysRadioPanelLayout.createSequentialGroup()
                .addGroup(daysRadioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sunRadio)
                    .addComponent(monRadio)
                    .addComponent(tueRadio)
                    .addComponent(wedRadio)
                    .addComponent(thuRadio)
                    .addComponent(friRadio)
                    .addComponent(satRadio))
                .addGap(0, 9, Short.MAX_VALUE))
        );

        timeStartAMPM.setFont(new java.awt.Font("MS UI Gothic", 0, 14)); // NOI18N
        timeStartAMPM.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AM", "PM" }));
        timeStartAMPM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                timeStartAMPMActionPerformed(evt);
            }
        });

        timeEndAMPM.setFont(new java.awt.Font("MS UI Gothic", 0, 14)); // NOI18N
        timeEndAMPM.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AM", "PM" }));
        timeEndAMPM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                timeEndAMPMActionPerformed(evt);
            }
        });

        timeStartLabel.setFont(new java.awt.Font("MS UI Gothic", 0, 14)); // NOI18N
        timeStartLabel.setText("Start");

        timeEndHourCmb.setFont(new java.awt.Font("MS UI Gothic", 0, 14)); // NOI18N
        timeEndHourCmb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "00", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", " " }));
        timeEndHourCmb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                timeEndHourCmbActionPerformed(evt);
            }
        });

        timeEndLabel.setFont(new java.awt.Font("MS UI Gothic", 0, 14)); // NOI18N
        timeEndLabel.setText("End");

        timeEndMinuteCmb.setFont(new java.awt.Font("MS UI Gothic", 0, 14)); // NOI18N
        timeEndMinuteCmb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "00", "10", "20", "30", "40", "50" }));
        timeEndMinuteCmb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                timeEndMinuteCmbActionPerformed(evt);
            }
        });

        timeStartHourCmb.setFont(new java.awt.Font("MS UI Gothic", 0, 14)); // NOI18N
        timeStartHourCmb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "00", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", " " }));
        timeStartHourCmb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                timeStartHourCmbActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("MS UI Gothic", 1, 14)); // NOI18N
        jLabel15.setText(":");

        timeStartMinuteCmb.setFont(new java.awt.Font("MS UI Gothic", 0, 14)); // NOI18N
        timeStartMinuteCmb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "00", "10", "20", "30", "40", "50" }));
        timeStartMinuteCmb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                timeStartMinuteCmbActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout timePanelLayout = new javax.swing.GroupLayout(timePanel);
        timePanel.setLayout(timePanelLayout);
        timePanelLayout.setHorizontalGroup(
            timePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, timePanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(timePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(timePanelLayout.createSequentialGroup()
                        .addGroup(timePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(timeStartLabel)
                            .addComponent(timeEndLabel))
                        .addGap(38, 38, 38)
                        .addGroup(timePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(timePanelLayout.createSequentialGroup()
                                .addComponent(timeEndAMPM, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(timeEndHourCmb, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(timeEndMinuteCmb, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(timePanelLayout.createSequentialGroup()
                                .addComponent(timeStartAMPM, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(timeStartHourCmb, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(14, 14, 14)
                                .addComponent(timeStartMinuteCmb, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(timePanelLayout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addComponent(jLabel15)))
                .addContainerGap())
        );
        timePanelLayout.setVerticalGroup(
            timePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(timePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(timePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(timeStartHourCmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(timeStartMinuteCmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(timeStartAMPM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(timeStartLabel))
                .addGap(8, 8, 8)
                .addGroup(timePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(timeEndAMPM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(timeEndHourCmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(timeEndMinuteCmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(timeEndLabel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        courseNumEntry.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));
        courseNumEntry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                courseNumEntryActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(mainPanelLayout.createSequentialGroup()
                                .addComponent(professorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29)
                                .addComponent(professorCmbbox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(mainPanelLayout.createSequentialGroup()
                                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(semesterLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                                        .addComponent(daysLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(timeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(29, 29, 29)
                                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(mainPanelLayout.createSequentialGroup()
                                        .addComponent(daysRadioPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(mainPanelLayout.createSequentialGroup()
                                        .addComponent(timePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                                        .addComponent(submitButton))
                                    .addComponent(semesterCmbbox, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(semesterAddButton)
                            .addComponent(professorAddButton, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addContainerGap())
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(courseNumLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(titleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(departmentLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(30, 30, 30)
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(mainPanelLayout.createSequentialGroup()
                                .addComponent(departmentCmbbox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(departmentAddButton))
                            .addComponent(titleEntry, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(courseNumEntry))
                        .addGap(12, 12, 12))))
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(departmentLabel)
                    .addComponent(departmentCmbbox, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(departmentAddButton, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(courseNumLabel)
                    .addComponent(courseNumEntry, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(titleEntry, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(titleLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(professorLabel)
                    .addComponent(professorCmbbox, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(professorAddButton, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(semesterAddButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(semesterLabel)
                        .addComponent(semesterCmbbox, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(daysLabel)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addComponent(daysRadioPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(timeLabel)
                            .addComponent(timePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(submitButton)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void timeStartMinuteCmbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_timeStartMinuteCmbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_timeStartMinuteCmbActionPerformed

    private void timeStartHourCmbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_timeStartHourCmbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_timeStartHourCmbActionPerformed

    private void timeEndMinuteCmbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_timeEndMinuteCmbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_timeEndMinuteCmbActionPerformed

    private void timeEndHourCmbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_timeEndHourCmbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_timeEndHourCmbActionPerformed

    private void timeEndAMPMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_timeEndAMPMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_timeEndAMPMActionPerformed

    private void timeStartAMPMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_timeStartAMPMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_timeStartAMPMActionPerformed

    private void thuRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_thuRadioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_thuRadioActionPerformed

    private void friRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_friRadioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_friRadioActionPerformed

    private void satRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_satRadioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_satRadioActionPerformed

    private void wedRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wedRadioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_wedRadioActionPerformed

    private void tueRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tueRadioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tueRadioActionPerformed

    private void monRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_monRadioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_monRadioActionPerformed

    private void sunRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sunRadioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sunRadioActionPerformed

    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed
        // TODO add your handling code here:
        setActive(false);
    }//GEN-LAST:event_submitButtonActionPerformed

    private void departmentAddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_departmentAddButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_departmentAddButtonActionPerformed

    private void professorAddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_professorAddButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_professorAddButtonActionPerformed

    private void semesterAddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_semesterAddButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_semesterAddButtonActionPerformed

    private void titleEntryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_titleEntryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_titleEntryActionPerformed

    private void courseNumEntryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_courseNumEntryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_courseNumEntryActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFormattedTextField courseNumEntry;
    private javax.swing.JLabel courseNumLabel;
    private javax.swing.JLabel daysLabel;
    private javax.swing.JPanel daysRadioPanel;
    private javax.swing.JButton departmentAddButton;
    private javax.swing.JComboBox<Department> departmentCmbbox;
    private javax.swing.JLabel departmentLabel;
    private javax.swing.JRadioButton friRadio;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JOptionPane jOptionPane1;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JRadioButton monRadio;
    private javax.swing.JButton professorAddButton;
    private javax.swing.JComboBox<Professor> professorCmbbox;
    private javax.swing.JLabel professorLabel;
    private javax.swing.JRadioButton satRadio;
    private javax.swing.JButton semesterAddButton;
    private javax.swing.JComboBox<Semester> semesterCmbbox;
    private javax.swing.JLabel semesterLabel;
    private javax.swing.JButton submitButton;
    private javax.swing.JRadioButton sunRadio;
    private javax.swing.JRadioButton thuRadio;
    private javax.swing.JComboBox<String> timeEndAMPM;
    private javax.swing.JComboBox<String> timeEndHourCmb;
    private javax.swing.JLabel timeEndLabel;
    private javax.swing.JComboBox<String> timeEndMinuteCmb;
    private javax.swing.JLabel timeLabel;
    private javax.swing.JPanel timePanel;
    private javax.swing.JComboBox<String> timeStartAMPM;
    private javax.swing.JComboBox<String> timeStartHourCmb;
    private javax.swing.JLabel timeStartLabel;
    private javax.swing.JComboBox<String> timeStartMinuteCmb;
    private javax.swing.JTextField titleEntry;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JRadioButton tueRadio;
    private javax.swing.JRadioButton wedRadio;
    // End of variables declaration//GEN-END:variables

}
